config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'

  get 'favorites/destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    collection do
      post :confirm
    end
  end

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :img, presence: true
  validates :title, presence: true,length: {maximum: 30}
  validates :comment, presence: true,length: {maximum: 255}


  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }

  validates :name, presence: true,length: {maximum: 30}
  validates :email, presence: true,length: {maximum: 255},
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :pictures, dependent: :destroy

  has_many :favorites, dependent: :destroy


  mount_uploader :icon, ImgUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :login_limit, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :user_limit, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end

  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver

        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:img, :title, :comment, :img_cache)
    end

    def login_limit
      if logged_in? ==false
        redirect_to new_session_path
      end
    end

    def user_limit
      if @picture.user_id != current_user.id
        redirect_to pictures_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @favorite_pictures = @user.favorites
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit_picture
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit_user
    if action_name == 'new' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#blog_navi" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "投稿写真一覧",pictures_path,class: 'navbar-brand'%>
      </div>
      <div class="collapse navbar-collapse" id="pictures_navi">
        <ul class="nav navbar-nav">
          <li><%= link_to_if(logged_in?,'PICTURE LISTS',pictures_path){link_to('PICTURE LISTS',new_session_path)} %></li>
          <li><%= link_to_if(logged_in?,'NEW PICTURE',new_picture_path){link_to('NEW PICTURE',new_session_path)} %></li>
        </ul>
      </div>
    </div>
  </nav>

  <body>
    <div class="contain clearfix">
      
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <%end%>

      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>
      <%= yield %>

      <footer>
        <p>運営会社DIVE INTO CODE株式会社</p>
        <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit_picture) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :img %>
    <%= image_tag(@picture.img.url) if @picture.img.url %>
    <p><%= form.file_field :img, id: :picture_img %></p>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :picture_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>Confirmation</h1>
<hr>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :comment %>
  <%= form.hidden_field :img_cache %>

  <%= image_tag(@picture.img) %><br>
  <p>タイトル:<%= @picture.title%></p><br>
  <p>内容:<%= @picture.comment%></p><br>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :img_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Infomation</h1>
<hr>

<div class="user_profile">
  <div class="login_user_icon">
    <% login_user = User.find(current_user.id)%>
    <%= image_tag(login_user.icon) %>
  </div>

  <div class="login_user_comment">
    <div class="login_user_name">
      <h2><%= login_user.name%></h2>
    </div>
  </div>
</div>

<h1>Pictures</h1>
<hr>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>投稿者</th>
      <th>Title</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <% user_info = User.find(picture.user_id)%>
        <tr>
          <td>
            <div class="picture_img">
            <%= image_tag picture.img %>
            </div>
          </td>
          <td>
            <div class="picture_field">
            <P><%= user_info.name%></P>
            </div>
          </td>
          <td>
            <div class="picture_field">
            <%= picture.title %>
            </div>
          </td>
          <td>
            <div class="picture_field">
            <%= picture.comment %>
            </div>
          </td>
          <td>
            <div class="picture_field">
              <%= link_to 'Show', picture, class: "btn btn-default" %>
            </div>
          </td>
          <% if picture.user_id == current_user.id %>
            <td>
              <div class="picture_field">
              <%= link_to 'Edit', edit_picture_path(picture), class: "btn btn-warning" %>
              </div>
            </td>
            <td>
              <div class="picture_field">
              <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </div>
            </td>
          <%end%>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<hr>
<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Picture</h1>
<hr>
<br>
<p>
  <strong>Img:</strong>
  <%= image_tag @picture.img %>
</p>
<br>
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>
<br>
<p>
  <strong>Comment:</strong>
  <%= @picture.comment %>
</p>
<br>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<br>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url:choose_new_or_edit_user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password_digest %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_digest %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :icon, id: :user_icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h1>Confirmation</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :password %>
  <%= form.hidden_field :password_confirmation %>
  <%= form.hidden_field :icon_cache %>

  <%= image_tag(@user.icon) %><br>
  <p>タイトル:<%= @user.name%></p><br>
  <p>内容:<%= @user.email%></p><br>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :icon_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>Email</th>
      <th>アイコン画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.icon %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<br>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<br>
<p>
  <strong>Icon:</strong>
  <%= image_tag(@user.icon) %>
</p>
<br>
<h2>お気に入り一覧</h2>

  <% @favorite_pictures.each do |favorite|%>
  <% picture = Picture.find(favorite.picture_id)%>
  写真タイトル：<%= picture.title%>
  投稿者：<% user_info = User.find(picture.user_id)%>
         <%= user_info.name%>
         <%= link_to 'ページへ行く',picture_path(picture.id)%><br>
  <%end%>
<%= link_to 'Edit', edit_user_path(@user) %>